# Generated by Django 3.0.1 on 2019-12-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('0', 'normal'), ('1', 'substitute'), ('2', 'additional')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Student')),
            ],
        ),
    ]
