# Generated by Django 3.0.1 on 2019-12-23 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191222_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='start_date_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='record',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='index.Record'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('0', 'normal'), ('1', 'substitute')], default='0', max_length=1),
        ),
    ]
