# Generated by Django 2.2.7 on 2019-11-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191126_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_attend',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
