# Generated by Django 3.0.1 on 2019-12-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191223_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='index.Course'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_class', to='index.CourseClass'),
        ),
    ]
