# Generated by Django 2.2.7 on 2019-11-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191126_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classes',
            name='time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
