# Generated by Django 3.0.1 on 2019-12-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191223_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='npm',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code',)},
        ),
        migrations.AlterUniqueTogether(
            name='courseclass',
            unique_together={('course', 'day', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='lecturer',
            unique_together={('npm',)},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('npm',)},
        ),
    ]
