# Generated by Django 2.2.7 on 2019-11-27 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191127_0022'),
        ('index', '0004_auto_20191126_2357'),
    ]

    operations = [
    ]
