# Generated by Django 3.0.1 on 2019-12-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20191223_1731'),
        ('index', '0004_auto_20191223_1228'),
    ]

    operations = [
    ]
