# Generated by Django 2.2.7 on 2019-12-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_merge_20191223_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='day',
            field=models.CharField(choices=[('0', 'MON'), ('1', 'TUE'), ('2', 'WED'), ('3', 'THU'), ('4', 'FRI'), ('5', 'SAT'), ('6', 'SUN')], max_length=1),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Substitute')], default='0', max_length=1),
        ),
    ]
