# Generated by Django 2.2.7 on 2019-12-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20191223_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='late_tolerance',
            field=models.IntegerField(default=10),
        ),
    ]
